#!/usr/bin/env python3
"""Generate chapters/appendix_prevalence.tex from tools/prevalence_data.py.
Columns: Disease | Common (%) | Females (%) | Males (%) | Children (%) | Old Age (%)
Each value = (per-1M count) / 10,000 -> percentage of a 1,000,000-person group.
"""
import ast, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

src = open(os.path.join(HERE, "prevalence_data.py")).read()
DATA = None
for node in ast.walk(ast.parse(src)):
    if isinstance(node, ast.Assign) and any(getattr(t, "id", "") == "DATA" for t in node.targets):
        DATA = ast.literal_eval(node.value)

# Disease names straight from the LaTeX chapter titles, sorted
want = set()
for f in os.listdir(os.path.join(ROOT, "chapters")):
    if not f.endswith(".tex") or f.startswith("appendix_"):
        continue
    t = re.search(r"\\chapter\{(.*)\}", open(os.path.join(ROOT, "chapters", f)).read())
    if t:
        want.add(t.group(1))
names = sorted(want)
# drop appendix-ish chapter titles that are not diseases
skip = {"Classification Table"}
names = [n for n in names if n not in skip]

missing = [n for n in names if n not in DATA]
if missing:
    raise SystemExit("Missing data for: %s" % missing)

def fmt(pct):
    """Format a percentage value compactly."""
    if pct == 0:
        return "0"
    if pct >= 100:
        return "100"
    if pct >= 10:
        return "%.0f" % pct
    if pct >= 1:
        return "%.1f" % pct
    if pct >= 0.01:
        return "%.2f" % pct
    return "%.3f" % pct

rows = []
for n in names:
    v = DATA[n]
    common, f, m, c, o = (x / 10000.0 for x in v)
    rows.append((n, common, f, m, c, o))

lines = []
lines.append("% Generated by tools/generate_prevalence_appendix.py -- do not edit by hand.")
lines.append("\\chapter*{Prevalence of Diseases by Demographic Group}")
lines.append("\\addcontentsline{toc}{chapter}{Prevalence of Diseases by Demographic Group}")
lines.append("")
lines.append("The table below reports the estimated percentage of a sample of 1,000,000")
lines.append("people affected in each demographic group: the general population (Common),")
lines.append("females, males, children, and older adults. Values are point-prevalence")
lines.append("estimates rounded from the epidemiology data presented in each chapter; 0")
lines.append("indicates that the condition is not normally encountered in that group, and")
lines.append("entries such as obstetric and gynecologic disorders apply only to females.")
lines.append("")
lines.append("\\begin{longtable}{@{}p{6.2cm}p{2.0cm}p{2.0cm}p{2.0cm}p{2.0cm}p{2.0cm}@{}}")
lines.append("\\toprule")
lines.append("\\textbf{Disease} & \\multicolumn{1}{c}{\\textbf{Common (\\%)}} &")
lines.append("\\multicolumn{1}{c}{\\textbf{Females (\\%)}} &")
lines.append("\\multicolumn{1}{c}{\\textbf{Males (\\%)}} &")
lines.append("\\multicolumn{1}{c}{\\textbf{Children (\\%)}} &")
lines.append("\\multicolumn{1}{c}{\\textbf{Old Age (\\%)}} \\\\")
lines.append("\\midrule")
lines.append("\\endhead")
lines.append("\\bottomrule")
lines.append("\\endfoot")
for n, c, f, m, ch, o in rows:
    esc = n.replace("&", "\\&").replace("%", "\\%").replace("#", "\\#")
    lines.append("%s & %s & %s & %s & %s & %s \\\\" % (esc, fmt(c), fmt(f), fmt(m), fmt(ch), fmt(o)))
lines.append("\\end{longtable}")

out = os.path.join(ROOT, "chapters", "appendix_prevalence.tex")
open(out, "w").write("\n".join(lines) + "\n")
print("wrote", out, "rows:", len(rows))
